---
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'

- include_tasks: distribution.yml
  when: os_packages

- include_tasks: upstream.yml
  when: not os_packages
