---
- name: Verify
  hosts: all
  gather_facts: true
  become: true

  vars:

    # path for installation from rclone-repos (os_packages=false)
    rclone_binary_path: "/usr/local/bin/rclone"

  tasks:

    - name: Set fact for distribution installation
      set_fact:
        rclone_binary_path: "/usr/bin/rclone"
      when: os_packages

    - name: Set fact for CentOS-7
      set_fact:
        rclone_binary_path: "/bin/rclone"
      when: os_packages and (ansible_distribution == "CentOS") and (ansible_distribution_major_version == "7")

    - name: "rclone - retrieve information"
      stat:
        path: '{{ rclone_binary_path }}'
      register: remote_file

    - name: "rclone - assert that file is created correctly"
      assert:
        that:
          - "remote_file.stat.exists"
          - "remote_file.stat.isreg"  # is a regular file
          - "remote_file.stat.path == '{{ rclone_binary_path }}'" # always true, but doesn't hurt
          - "remote_file.stat.mode == '0755'"

    - name: "rclone - check version"
      command: "{{ rclone_binary_path }} version"  # noqa 301
      register: shell_result_one

    - debug:
        var: shell_result_one.stdout_lines
