---
- name: Verify
  hosts: all
  gather_facts: true
  become: true

  tasks:

    - debug: var=ansible_distribution
    - debug: var=ansible_distribution_major_version
    - debug: var=ansible_os_family

    - name: Gather main variables
      include_vars: '../../defaults/main.yml'

    - name: Gather OS specific variables
      include_vars: "{{ item }}"
      with_first_found:
        - '../../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '../../vars/{{ ansible_distribution }}.yml'
        - '../../vars/{{ ansible_os_family }}.yml'

    - debug: var=rclone_binary_path

    - name: "rclone - retrieve information"
      stat:
        path: '{{ rclone_binary_path }}'
      register: remote_file
      when: not os_packages

    #- debug: var=remote_file.stat

    - name: "rclone - assert that file is created correctly"
      assert:
        that:
          - "remote_file.stat.exists"
          - "remote_file.stat.isreg"  # is a regular file
          #  - "remote_file.stat.path == '{{ rclone_binary_path }}'"
          - "remote_file.stat.mode == '0755'"

    - name: "rclone - check version"
      command: "{{ rclone_binary_path }} version"  # noqa 301
      register: shell_result_one
      when: not os_packages

    - debug:
        var: shell_result_one.stdout_lines
